"""Data-access semantics for observations."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Select, select
from sqlalchemy.orm import Session

from ..schemas import Observation
from .models import ObservationRow


class ObservationRepository:
    """Persist and query observations without owning transaction boundaries."""

    def __init__(self, session: Session) -> None:
        self._session = session

    def append(self, obs: Observation) -> None:
        """Stage one observation insert in the caller's transaction."""
        self._session.add(
            ObservationRow(
                id=uuid.UUID(obs.id),
                timestamp=_parse_timestamp(obs.timestamp),
                place=obs.place,
                obs_date=obs.obs_date,
                time_of_day=obs.time_of_day,
                species=obs.species,
                count=obs.count,
                behavior=obs.behavior,
                raw_note=obs.raw_note,
                confidence=obs.confidence,
                source=obs.source,
                flags=list(obs.flags),
            )
        )
        self._session.flush()

    def query(
        self,
        place: str | None = None,
        species: str | None = None,
        date_range: str | None = None,
    ) -> list[Observation]:
        """Return matching observations in stable insertion order."""
        statement: Select[tuple[ObservationRow]] = select(ObservationRow)
        if place is not None:
            statement = statement.where(
                ObservationRow.place.is_not(None),
                ObservationRow.place.contains(place, autoescape=True),
            )
        if species is not None:
            statement = statement.where(
                ObservationRow.species.is_not(None),
                ObservationRow.species.contains(species, autoescape=True),
            )
        statement = _apply_date_range(statement, date_range)
        rows = self._session.scalars(statement.order_by(ObservationRow.sequence_no)).all()
        return [_to_observation(row) for row in rows]


def _apply_date_range(
    statement: Select[tuple[ObservationRow]],
    date_range: str | None,
) -> Select[tuple[ObservationRow]]:
    """Apply the legacy `start..end` lexicographic date filter."""
    if date_range is None or ".." not in date_range:
        return statement
    start, _, end = date_range.partition("..")
    start, end = start.strip(), end.strip()
    statement = statement.where(ObservationRow.obs_date.is_not(None))
    if start:
        statement = statement.where(ObservationRow.obs_date >= start)
    if end:
        statement = statement.where(ObservationRow.obs_date <= end)
    return statement


def _parse_timestamp(value: str) -> datetime:
    """Parse the ISO timestamp generated by AppendLogTool."""
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def _to_observation(row: ObservationRow) -> Observation:
    """Map a database row back to the provider-neutral pydantic model."""
    return Observation(
        id=str(row.id),
        timestamp=row.timestamp.isoformat(),
        place=row.place,
        obs_date=row.obs_date,
        time_of_day=row.time_of_day,
        species=row.species,
        count=row.count,
        behavior=row.behavior,
        raw_note=row.raw_note,
        confidence=row.confidence,
        source=row.source,
        flags=list(row.flags),
    )
